# O atributo 'version' no topo foi removido.

services:
  php-fluentpdo:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: taskmanager_php_fluentpdo
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy # Ajustado para esperar MySQL saudável
    networks:
      - task-network
    environment:
      APP_ENV: development

  php-medoo:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: taskmanager_php_medoo
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy # Ajustado para esperar MySQL saudável
    networks:
      - task-network
    environment:
      APP_ENV: development

  mysql:
    image: mysql:8.0
    container_name: taskmanager_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_manager_db
      MYSQL_USER: taskmanager_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-P", "3306", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:latest
    container_name: taskmanager_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/ssl/:/etc/nginx/ssl/
    depends_on:
      php-fluentpdo:
        condition: service_started
      php-medoo:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - task-network
    extra_hosts:
      - "projetofluentpdo.test:127.0.0.1"
      - "projetomedoo.test:127.0.0.1"

networks:
  task-network:
    driver: bridge

volumes:
  mysql-data: